-- amagi viewership
insert into "NOSEY"."PUBLIC".amagi_viewership( VIEW_DATE, CHANNEL, CHANNEL_NAME, CONTENT_ID, CONTENT_NAME, SESSION_COUNT, TOTAL_VIEWERSHIP_MINUTES, UNIQUE_VIEWERS, AVG_SESSION_COUNT, AVG_SESSION_DURATION_PER_SESSION, AVG_SESSION_DURATION_PER_VIEWER, MONTH, REF_ID, SHARE, REVENUE, DEAL_PARENT, TERRITORY_ID, YEAR, QUARTER, SHARE_CALCULATED, CALC_REVENUE, DATE_INTERVAL, CHANNEL_ID, ID, SERIES, COUNTRY, DEVICE, DEVICE_ID, CALC_SHARE)
select VIEW_DATE, CHANNEL, CHANNEL_NAME, CONTENT_ID, CONTENT_NAME, SESSION_COUNT, TOTAL_VIEWERSHIP_MINUTES, UNIQUE_VIEWERS, AVG_SESSION_COUNT, AVG_SESSION_DURATION_PER_SESSION, AVG_SESSION_DURATION_PER_VIEWER, MONTH, REF_ID, SHARE, REVENUE, DEAL_PARENT, TERRITORY_ID, YEAR, QUARTER, SHARE_CALCULATED, CALC_REVENUE, DATE_INTERVAL, CHANNEL_ID, ID, SERIES, COUNTRY, DEVICE, DEVICE_ID, CALC_SHARE
from amagi_viewership where quarter = 'q3' and year = 2021



-- wurl viewership
insert into "NOSEY"."PUBLIC".wurl_viewership( 
        TITLE, CHANNEL, AVG_SESSION_HOV, TOT_HOV, OCCURANCES, TOT_COMPLETIONS, TOT_SESSIONS, VS, MONTH, REF_ID, DEAL_PARENT, TERRITORY_ID, PLAY_COUNT, TOTAL_TIME_WATCHED, ASSET_DURATION, AVG_PLAY_TIME, AVG_PLAYTHROUGH_RATE, ASSET_ID, SHARE_CALCULATED, REVENUE, TOT_AIRTIME_MIN, TOT_EPISODE_HOV, MONTHLY_SHARE, SHARE_2, PAYOUT, QUARTER, YEAR, FILENAME, CALC_REVENUE, SERIES, CHANNEL_ID, SHARE)
select  TITLE, CHANNEL, AVG_SESSION_HOV, TOT_HOV, OCCURANCES, TOT_COMPLETIONS, TOT_SESSIONS, VS, MONTH, REF_ID, DEAL_PARENT, TERRITORY_ID, PLAY_COUNT, TOTAL_TIME_WATCHED, ASSET_DURATION, AVG_PLAY_TIME, AVG_PLAYTHROUGH_RATE, ASSET_ID, SHARE_CALCULATED, REVENUE, TOT_AIRTIME_MIN, TOT_EPISODE_HOV, MONTHLY_SHARE, SHARE_2, PAYOUT, QUARTER, YEAR, FILENAME, CALC_REVENUE, SERIES, CHANNEL_ID, SHARE
from wurl_viewership where quarter = 'q3' and year = 2021

-- pluto
insert into "NOSEY"."PUBLIC".pluto_viewership(  TITLE, MONTH,PARNTER_NAME,CLIP_NAME,TOTAL_VIEWING_MINUTES,REF_ID,REVENUE,SESSIONS,DEAL_PARENT,YEAR,QUARTER,SERIES,SHARE_CALCULATED,CALC_REVENUE,FILENAME,CHANNEL_Id,TERRITORY_ID,CHANNEL ) 
select  TITLE, MONTH,PARNTER_NAME,CLIP_NAME,TOTAL_VIEWING_MINUTES,REF_ID,REVENUE,SESSIONS,DEAL_PARENT,YEAR,QUARTER,SERIES,SHARE_CALCULATED,CALC_REVENUE,FILENAME,CHANNEL_Id,TERRITORY_ID,CHANNEL
from pluto_viewership
where quarter = 'q3' and year = 2021



-- revenue 
insert into "NOSEY"."PUBLIC".revenue ( MONTH, YEAR, QUARTER, REVENUE, DEAL_PARENT, YEAR_MONTH_DAY, PROVIDER, PARTNER, PARTNER_REVENUE, MAX_COSTS, COSTS, REVENUE_SPLIT, CPMS, CHANNEL, TYPE, TITLE, INVOICE_NUMBER, IMPRESSIONS, ECPM, CHANNEL_ID, TERRITORY_ID, PRODUCT, PARTNER_ITEM_ID, TERRITORY, GROSS_REVENUE, NET_REVENUE, FILENAME, DATE_UNFORMATTED, DEVICE_ID) 
select MONTH, YEAR, QUARTER, REVENUE, DEAL_PARENT, YEAR_MONTH_DAY, PROVIDER, PARTNER, PARTNER_REVENUE, MAX_COSTS, COSTS, REVENUE_SPLIT, CPMS, CHANNEL, TYPE, TITLE, INVOICE_NUMBER, IMPRESSIONS, ECPM, CHANNEL_ID, TERRITORY_ID, PRODUCT, PARTNER_ITEM_ID, TERRITORY, GROSS_REVENUE, NET_REVENUE, FILENAME, DATE_UNFORMATTED, DEVICE_ID
from revenue where quarter = 'q3' and year = 2021


-- monthly revenue 
insert into "NOSEY"."PUBLIC".monthly_revenue( YEAR_MONTH_DAY, REVENUE, DEAL_PARENT, MONTH, YEAR, QUARTER, CHANNEL, CHANNEL_ID, TERRITORY_ID) 
select YEAR_MONTH_DAY, REVENUE, DEAL_PARENT, MONTH, YEAR, QUARTER, CHANNEL, CHANNEL_ID, TERRITORY_ID
from monthly_revenue where quarter = 'q3' and year = 2021

-- monthly viewership
insert into "NOSEY"."PUBLIC".monthly_viewership(DEAL_PARENT, MONTH, YEAR, QUARTER, TOT_HOV, CHANNEL, TERRITORYID, CHANNEL_ID, YEAR_MONTH_DAY)
select DEAL_PARENT, MONTH, YEAR, QUARTER, TOT_HOV, CHANNEL, TERRITORYID, CHANNEL_ID, YEAR_MONTH_DAY 
from monthly_viewership where quarter = 'q3' and year = 2021 



-- quarterly viewership
insert into "NOSEY"."PUBLIC".quarterly_viewership (DEAL_PARENT, YEAR, QUARTER, TOT_HOV, CHANNEL, TERRITORYID)
select DEAL_PARENT, YEAR, QUARTER, TOT_HOV, CHANNEL, TERRITORYID  
from quarterly_viewership where quarter = 'q3' and year = 2021


-- quarterly revenue 
insert into "NOSEY"."PUBLIC".quarterly_revenue(DEAL_PARENT,YEAR,QUARTER,REVENUE, CHANNEL)
select DEAL_PARENT,YEAR,QUARTER,REVENUE, CHANNEL
from quarterly_revenue where quarter = 'q3' and year = 2021