//split viewership 
SELECT TRY_CAST(SPLIT_PART(TOTAL_TIME_WATCHED, ':',1)as INTEGER)*60 + TRY_CAST(SPLIT_PART(TOTAL_TIME_WATCHED, ':',2)as INTEGER) + TRY_CAST(SPLIT_PART(TOTAL_TIME_WATCHED, ':',3)as INTEGER)/60, TOT_HOV FROM WURL_VIEWERSHIP WHERE deal_parent = 17
